apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/namespace.yaml
  - k8s/configmap.yaml
  - k8s/mariadb.yaml
  - k8s/application.yaml

configMapGenerator:
  - name: mariadb-init
    namespace: web-course
    files:
      - 01-schema.sql=mariadb-init/01-schema.sql
      - 02-seed.sql=mariadb-init/02-seed.sql