apiVersion: v1
kind: Secret
metadata:
  name: web-course-secrets
  namespace: web-course
type: Opaque
stringData:
  MARIADB_USER: CHANGE_ME
  MARIADB_PASSWORD: CHANGE_ME
  MARIADB_ROOT_PASSWORD: CHANGE_ME
  JWT_SECRET: CHANGE_ME_TO_A_LONG_RANDOM_VALUE